version: "3.7"

networks:
  Sistem:
    driver: bridge
services:
  backend:
    build: ./Api/Client
    depends_on:
      - server
    volumes:
      - ./Api/Client:/app    
    networks:
      - Sistem
    ports:
      - "3000:3000"
  server:
    build: ./Api/Server
    networks:
      - Sistem
    volumes:
      - ./Api/Server:/app
    ports:
      - "8000:8000"
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - Sistem
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: 'bitnami/kafka:2.8.1'
    networks:
     - Sistem
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
 